### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by farhankn** [thingdeux/bias-exposed#1]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/farhan/Downloads/bias-exposed-master/bias/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/farhan/Downloads/bias-exposed-master/bias/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 376, in execute
    sys.stdout.write(self.main_help_text() + '\n')
  File "/home/farhan/Downloads/bias-exposed-master/bias/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 240, in main_help_text
    for name, app in six.iteritems(get_commands()):
  File "/home/farhan/Downloads/bias-exposed-master/bias/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/home/farhan/Downloads/bias-exposed-master/bias/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/farhan/Downloads/bias-exposed-master/bias/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/farhan/Downloads/bias-exposed-master/bias/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/farhan/Downloads/bias-exposed-master/bias/local/lib/python2.7/site-packages/django/utils/importlib.py", line 33, in import_module
    raise TypeError("relative imports require the 'package' argument")
TypeError: relative imports require the 'package' argument

```

**Comment by thingdeux** [comment]
Hi,

I stopped working on this ages ago else I would have documented some of this. I'm general you do not want to leave your secret key hanging around in your repo, so if you try to run this either create a local_settings.py file and include the secret key or simply include secret key in settings.py.

You can find out more here - https://docs.djangoproject.com/en/1.9/ref/settings/
